<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>merchant_name</name>
   <tag></tag>
   <elementGuidId>53cb8080-1a74-45e0-b0ac-075877bd81ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[@id='merchant_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[@id='merchant_name']</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/checkout/iframe/iframe1</value>
   </webElementProperties>
</WebElementEntity>
